export const RECEIVE_ANIMAL_LIST = 'RECEIVE_ANIMAL_LIST';
export const RECEIVE_ADOPTED_LIST = 'RECEIVE_ADOPTED_LIST';
export const RECEIVE_NOT_ADOPTED = 'RECEIVE_NOT_ADOPTED';
export const RECEIVE_CLIENT_LIST = 'RECEIVE_CLIENT_LIST';
